---
id: Autoloader_Cache
name: Autoloader_Cache
full: Caching library for Horde_Autoloader
description: |
  An extension of the Horde autoloader that implements caching of class-file-maps. The caching method is determined automatically from the list of supported cache backends: APC, XCache, eAccelerator, local file system.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Autoloader_Cache
authors:
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
  -
    name: Michael Slusarz
    user: slusarz
    email: slusarz@horde.org
    active: false
    role: developer
version:
  release: 3.0.0alpha1
  api: 3.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^7
    composer:
      horde/autoloader: ^3
    ext:
      json: '*'
  optional:
    ext:
      horde_lz4: '*'
      lzf: '*'
      msgpack: '*'
      apc: '*'
      eaccelerator: '*'
      xcache: '*'
